### ISSUE TITLE
`RevealSdkSettings.serverUrl` property cannot be set inside `OnInit` if the `dashboard` property is not bound

### ISSUE THREAD

**Issue by dafo** [RevealBi/revealbi-ui#8]
**Steps to reproduce:**
1. Clone https://github.com/dafo/dashboardPropertyExample where:
`ngOnInit() {
    RevealSdkSettings.serverUrl = this.stateService.myURL;
  }` and `<rv-reveal-view dashboard="Sales" [options]="dashboardOptions" class="reveal-dash-board"></rv-reveal-view>`
3. Run npm i
4. Run npm run start

**Actual result:** 
The dashboard is not correctly loaded

**Expected result:**
The dashboard is loaded

**Note:** This is working fine if we create a variable and bind the `dashboard` property to it. Like this:
Inside the logic file we add:
`public dashboardName = 'Sales';`
and the .html file is like that:
`<rv-reveal-view [dashboard]="dashboardName" [options]="dashboardOptions" class="reveal-dash-board"></rv-reveal-view>`

**Comment by brianlagunas** [comment]
This is not a bug, but rather by design. First off, the `RevealSdkSettings.serverUrl` is an app level setting, and should not be set in any type of component lifecycle event such as ngOnInit. It is a global setting that should be set once on app startup.

In this specific case, the reason this happens is because the web component loads before the ngOnInit executes. When you create a binding, the bindings aren't bound until later in the component lifecycle which is why it works in that case. Really, the main issue is the timing of when things are happening.
